@echo off
rem chcp first: this file is UTF-8 and the console defaults to the system codepage, so without it
rem every Korean message below arrives as mojibake at exactly the moment something went wrong.
chcp 65001 >nul
rem Generated by autonomous-game-studio. Runs this Godot project.
rem Set GODOT_EXECUTABLE to override which engine build is used.
setlocal
if not "%GODOT_EXECUTABLE%"=="" set "GODOT="%GODOT_EXECUTABLE%""
if "%GODOT%"=="" set "GODOT="C:\dev\godot\Godot_v4.7.2-stable_win64.exe""
if not exist %GODOT% (
  echo Godot 실행 파일을 찾을 수 없습니다: %GODOT%
  echo GODOT_EXECUTABLE 환경 변수로 경로를 지정하세요.
  pause
  exit /b 1
)
echo %GODOT% --path "%~dp0."
%GODOT% --path "%~dp0."
if errorlevel 1 pause
endlocal
