"""Tools the code agent uses when a run is building a Godot game instead of an HTML one.

The HTML tools assume the game is one file. A Godot game is a directory - project.godot, scenes,
scripts, imported assets - so the write/inspect/verify loop is the same shape but addressed by
path, and the verification step is the engine itself rather than a keyword scan.

Everything writes inside the run's own workspace, which is also the Godot project root. That is
deliberate: sprites generated by generate_comfyui_image land in <workspace>/assets, so the agent
can reference them as res://assets/<name>.png with no copying step and no second asset location to
keep in sync.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Annotated

from langchain_core.tools import tool
from langgraph.prebuilt import InjectedState

from .agent_tools import (
    _draft_path,
    generate_comfyui_image,
    list_game_assets,
    required_gap,
)
from .godot import check_scripts, godot_available, run_project, static_project_qa
from .required_art import missing_required_finding

# What the agent is allowed to write. A Godot project is mostly text, and the binary formats it
# might otherwise reach for (.res, .scn, .import) are produced by the engine on import - a model
# writing one by hand produces a corrupt project that fails in a way nothing here can explain.
WRITABLE_SUFFIXES = {".gd", ".tscn", ".tres", ".godot", ".cfg", ".json", ".txt", ".md", ".svg"}
# Never handed back to the agent or counted as project source: the import cache is engine-owned,
# large, and regenerated on every run.
_ENGINE_OWNED = (".godot", "build", ".import")
MAX_PROJECT_FILES = 60


def _project_dir(state: dict) -> Path:
    """The run's workspace, which is the Godot project root."""
    return _draft_path(state).parent


def _resolve(state: dict, path: str) -> Path:
    """Resolve an agent-supplied path inside the project, or refuse it.

    The path arrives as free text from a model, so this is a boundary, not a formality: a traversal
    or an absolute path would write outside the run's workspace.
    """
    cleaned = str(path or "").strip().replace("\\", "/")
    cleaned = re.sub(r"^res://", "", cleaned).lstrip("/")
    if not cleaned:
        raise ValueError("빈 경로입니다.")
    root = _project_dir(state).resolve()
    target = (root / cleaned).resolve()
    if not target.is_relative_to(root):
        raise ValueError(f"프로젝트 밖의 경로입니다: {path}")
    if target.suffix.lower() not in WRITABLE_SUFFIXES:
        raise ValueError(
            f"쓸 수 없는 확장자입니다: {target.suffix or '(없음)'}. "
            f"허용: {', '.join(sorted(WRITABLE_SUFFIXES))}. 이미지는 generate_comfyui_image를 쓰세요."
        )
    return target


def _project_files(root: Path) -> list[Path]:
    return sorted(
        path for path in root.rglob("*")
        if path.is_file()
        and path.suffix.lower() in WRITABLE_SUFFIXES
        and not any(part in _ENGINE_OWNED or part.endswith(".import") for part in path.parts)
    )


@tool
def write_godot_file(path: str, content: str, state: Annotated[dict, InjectedState]) -> str:
    """Create or replace one text file in the Godot project (a scene, a script, project.godot).

    path is relative to the project root; "res://" is accepted and stripped. Write complete files -
    a partial script is a parse error, not a draft. Start with project.godot, then the main scene
    and its script.
    """
    try:
        target = _resolve(state, path)
    except ValueError as error:
        return f"Rejected: {error}"
    body = content if content.endswith("\n") else content + "\n"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(body, encoding="utf-8")
    relative = target.relative_to(_project_dir(state).resolve()).as_posix()
    remaining = [p.name for p in _project_files(_project_dir(state).resolve())]
    if "project.godot" not in remaining:
        return (f"Wrote res://{relative} ({len(body.splitlines())} lines). "
                "프로젝트에 아직 project.godot이 없습니다. 먼저 만드세요.")
    return (f"Wrote res://{relative} ({len(body.splitlines())} lines). "
            "프로젝트가 완성되면 run_godot_qa를 호출하세요.")


@tool
def read_godot_file(
    state: Annotated[dict, InjectedState],
    path: str = "",
    start_line: int = 0,
    end_line: int = 0,
    outline: bool = False,
) -> str:
    """Read one project file, whole or in part, so it can be inspected or repaired.

    Whatever comes back stays in this conversation and is re-sent on every later turn, so read
    narrowly. outline=True returns a numbered map of the file's functions and nodes; start_line and
    end_line (1-based, inclusive) return just the section at fault.
    """
    try:
        target = _resolve(state, path)
    except ValueError as error:
        return f"Rejected: {error}"
    if not target.is_file():
        return f"res://{path} 이 없습니다. list_godot_files로 확인하세요."
    lines = target.read_text(encoding="utf-8").splitlines()
    if outline:
        marks = [f"{number:>4}: {line.strip()[:110]}" for number, line in enumerate(lines, 1)
                 if re.search(r"^\s*(func |var |const |class |signal |\[node|\[ext_resource|extends )", line)]
        return (f"{len(lines)} lines. Structure:\n" + "\n".join(marks[:120])) if marks \
            else f"{len(lines)} lines; no recognizable structure markers."
    if start_line or end_line:
        first, last = max(1, start_line or 1), min(len(lines), end_line or len(lines))
        if first > last:
            return f"Invalid range: the file has {len(lines)} lines."
        body = "\n".join(f"{n:>4}: {lines[n - 1]}" for n in range(first, last + 1))
        return f"Lines {first}-{last} of {len(lines)}:\n{body}"
    return "\n".join(lines)


@tool
def list_godot_files(state: Annotated[dict, InjectedState]) -> str:
    """List the project's own files with their sizes. Engine-generated import caches are hidden."""
    root = _project_dir(state).resolve()
    files = _project_files(root)
    if not files:
        return "프로젝트가 비어 있습니다. write_godot_file로 project.godot부터 만드세요."
    listing = "\n".join(
        f"res://{path.relative_to(root).as_posix()} ({len(path.read_text(encoding='utf-8', errors='replace').splitlines())} lines)"
        for path in files[:MAX_PROJECT_FILES]
    )
    more = f"\n… 외 {len(files) - MAX_PROJECT_FILES}개" if len(files) > MAX_PROJECT_FILES else ""
    return f"Godot project files:\n{listing}{more}"


@tool
def run_godot_qa(state: Annotated[dict, InjectedState]) -> str:
    """Compile every script and actually run the game headlessly, then report what broke.

    This is a real execution of the game, not a source inspection: a parse error, a null
    dereference in _ready, a missing scene, a bad node path or an autoload that does not exist all
    come back with the file and line that caused them. Fix what it reports and call it again.
    """
    root = _project_dir(state).resolve()
    if not (root / "project.godot").is_file():
        return json.dumps({"status": "repair", "findings": ["project.godot이 없습니다."]},
                          ensure_ascii=False)
    if not godot_available():
        return json.dumps({
            "status": "skipped",
            "findings": ["Godot 실행 파일을 찾을 수 없어 검증을 건너뛰었습니다."],
        }, ensure_ascii=False)
    if missing := required_gap(state):
        return json.dumps({"status": "repair", "stage": "required-art",
                           "findings": [missing_required_finding(missing)]}, ensure_ascii=False)
    assets = root / "assets"
    sprites = sorted(p.name for p in assets.glob("*.png")) if assets.is_dir() else []
    # Free, and it sees what the engine cannot: a project that starts and does nothing.
    structure = static_project_qa(root, sprites)
    if not structure.ok:
        return json.dumps({"status": "repair", "stage": "project-structure",
                           "findings": structure.findings}, ensure_ascii=False)
    scripts = check_scripts(root)
    if not scripts.ok:
        return json.dumps({"status": "repair", "stage": "script-compile",
                           "findings": scripts.findings}, ensure_ascii=False)
    played = run_project(root)
    return json.dumps({
        "status": "pass" if played.ok else "repair",
        "stage": "headless-run",
        "findings": played.findings + structure.findings,
    }, ensure_ascii=False)


# The code agent owns art here exactly as it does for HTML: generate_comfyui_image writes into
# <workspace>/assets, which is res://assets in this project, so a sprite is referenced by the path
# it was created at.
GODOT_TOOLS = [
    write_godot_file, read_godot_file, list_godot_files, run_godot_qa,
    list_game_assets, generate_comfyui_image,
]
